name: Git sync

on: workflow_dispatch

jobs:
  git-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: git-sync
        uses: wei/git-sync@55c6b63b4f21607da0e9877ca9b4d11a29fc6d83 # v3.0.0
        with:
          source_repo: https://gitlab.com/antora/antora-ui-default.git
          source_branch: master
          destination_repo: "https://github-actions[bot]:${{ github.token }}@github.com/${{ github.repository }}.git"
          destination_branch: upstream
